/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.view;

import javax.swing.JButton;

/**
 *
 * @author Anne Gitau
 */
public class ReportsView extends javax.swing.JDialog {

    /**
     * Creates new form ReportsView
     * @param parent
     * @param modal
     */
    public ReportsView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public JButton getStudentReports(){
        return studentsReportsButton;
    }
    public JButton getStaffReports(){
        return staffReportsButton;
    }
    public JButton getClassReports(){
        return classReportsButton;
    }
    public JButton getStreamReports(){
        return streamReportsButton;
    }
    public JButton getFeePaymentReports(){
        return feePaymentReportsButton;
    }
public JButton getExitReports(){
    return exitReportsButton;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentsReportsButton = new javax.swing.JButton();
        staffReportsButton = new javax.swing.JButton();
        classReportsButton = new javax.swing.JButton();
        exitReportsButton = new javax.swing.JButton();
        feePaymentReportsButton = new javax.swing.JButton();
        streamReportsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("REPORTS");

        studentsReportsButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        studentsReportsButton.setText("STUDENTS REPORTS");

        staffReportsButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        staffReportsButton.setText("STAFF REPORTS");

        classReportsButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        classReportsButton.setText("CLASS REPORTS");

        exitReportsButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exitReportsButton.setText("EXIT");

        feePaymentReportsButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        feePaymentReportsButton.setText("FEE PAYMENT REPORTS");

        streamReportsButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        streamReportsButton.setText("STREAM REPORTS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exitReportsButton)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(feePaymentReportsButton)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentsReportsButton)
                            .addComponent(streamReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classReportsButton)
                    .addComponent(staffReportsButton))
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentsReportsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staffReportsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classReportsButton)
                .addGap(17, 17, 17)
                .addComponent(streamReportsButton)
                .addGap(18, 18, 18)
                .addComponent(feePaymentReportsButton)
                .addGap(31, 31, 31)
                .addComponent(exitReportsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReportsView dialog = new ReportsView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton classReportsButton;
    private javax.swing.JButton exitReportsButton;
    private javax.swing.JButton feePaymentReportsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton staffReportsButton;
    private javax.swing.JButton streamReportsButton;
    private javax.swing.JButton studentsReportsButton;
    // End of variables declaration//GEN-END:variables
}
